Fix: Add missing pico/stdlib.h include to test_phase9.c
Fixes implicit declaration warning for sleep_ms() function.

Warning fixed:
  test_phase9.c:156: implicit declaration of function 'sleep_ms'

Change:
  Added #include "pico/stdlib.h" for Pico SDK time functions